### PR TITLE
Update to jsdom 4.x

### LINKED ISSUE #12: Update jsdom to remove native module dependency
Would be awesome

### PR DESCRIPTION
**Pull request by domenic**
Fixes #12

### CODE REVIEW

**Comment by domenic** [comment]
Tacked on an Ecmarkdown update while I was at it. Might fix #9.

**Comment by bterlson** [comment]
The only problem I have with this is dropping support for Node - I'd prefer to support all node-like hosts unless there's a good reason not to. Is there a way around it other than dropping jsdom?

**Comment by domenic** [comment]
Not really. If it helps, just think of it as only supporting modern versions of Node, instead of year-old ones. (Node is to io.js as IE is to Spartan.)

**Comment by michaelficarra** [comment]
@domenic That's disingenuous. Node 0.12 was released last month.

**Comment by domenic** [comment]
Bump? Should I publish a fork?

**Comment by bterlson** [comment]
Sad to lose node compat but I guess this is fine until the grand unification happens (hopefully) :)

**Comment by domenic** [comment]
Awesome, thanks! New npm version please? :)

**Comment by bterlson** [comment]
1.1.0 just for you, sir!

**Pull request merged**
