### PR TITLE
Patch __awaiter to use bluebird

### PR DESCRIPTION
**Pull request by rbuckton**
Keep in mind that even with this patch, the return **type** of an async function will still be the ES6 Promise, even though the runtime value will be a bluebird Promise.

### CODE REVIEW

**Comment by domenic** [comment]
Why? This seems like crazy black magic. It would be nicer to get rid of Bluebird and just use native promises?

**Comment by rbuckton** [comment]
@bterlson requested it. I'd prefer to use native promises as well.

**Comment by domenic** [comment]
I guess it would be good to at least add a comment linking to the docs on `__awaiter`.

**Comment by rbuckton** [comment]
@domenic Added in de98f8c

**Comment by bterlson** [comment]
@domenic the key reason is perf - using bluebird and the __awaiter override shaves ~3s off the ECMA262 build process. Will document it better.

**Comment by bterlson** [comment]
Committed some extra rationale in 33da4fb. Closing this as I've incorporated all the changes here as part of my previous commits.

**Comment by bterlson** [comment]
Make that 662f3a2.

**Pull request closed without merging**
